### ISSUE TITLE
Callback Mechanism Description

### ISSUE THREAD

**Issue by faragom** [EC-SEAL/dashboard#2]
# Callback mechanism

## Client
1. Register a URL callback with `/cl/callback` api
    * The URL must be in the same domain as the 
        client (to avoid cross-domain security restrictions)
    * A non-server allocated client (i.e. mobile client) can 
        use captive URL handlers to trigger the behaviour of this 
        callback, but on the client-side

2. Callback URL will be used by all redirect-accessed modules 
    to **return the control back to the client**
    * Will include a **response status object**, as described below
    
3. Callback URL must expect a POST parameter named `msToken`.

4. Pass the content of `msToken` to the `/cl/token/validate` api.
    * After validating the token, it will return an object 
    of this type, containing the validation response:
        
        ```yaml
        SessionMngrResponse:
          type: object
          properties:
            additionalData:
              type: string
            code:
              type: string
              enum:
                - OK
                - ERROR
                - NEW
            error:
              type: string
            sessionData:
              $ref: '#/definitions/MngrSessionTO'
          title: SessionMngrResponse
      
        MngrSessionTO:
          type: object
          required: [sessionId]
          properties:
            sessionId:
              type: string
            sessionVariables:
              type: object
          title: MngrSessionTO
        ```
      
5. Process the object (let's call it `resp`):
    1. if `resp.code != OK`, prompt error, as token is tampered or
        we don't trust the issuer
    2.if `resp.code == OK`, 
        * `resp.sessionData.sessionId` will contain the 
            sessionID. As a security measure, compare it with
            the sessionID the client will most probably already 
            have.
        * `resp.additionalData` will contain a status module for 
        the module response:
            ```yaml
            statusResponse:
              primaryCode:
                description: generic status description object
                type: string
                enum:
                  - OK
                  - ERROR
              secondaryCode:
                type: string
                description: Optional field for module specific status codes
              message:
                type: string
                description: Any message that might be of use to understand the status
            ```
6. `resp.additionalData` will have at least an `OK` or `ERROR` 
    primary code, probably an error message on error (not for 
    display, as it comes in a single language, just for logging), 
    and depending on the module, maybe a secondary status code 
    specific to the module.
    
7. Once the callback is validated, the client must recover control.
   If the client gave full control, redirect to the script to retake 
   the logic. If the client opened this redirect in an iframe or 
   window, signal the parent to get the state and close the window.
   
## Module
If your module is invoked through a redirection, when you are done
and want to return control to the client, you have to do the 
following:

1. Read the callback address from the Session Manager 
variable: `ClientCallbackAddr`

2. Build your own response status object:
    ```yaml
      statusResponse:
        primaryCode:
          description: generic status description object
          type: string
          enum:
            - OK
            - ERROR
        secondaryCode:
          type: string
          description: Optional field for module specific status codes
        message:
          type: string
          description: Any message that might be of use to understand the status
    ```
    If you need to specify specific secondary codes (unlikely), 
    and expect the client to behave differently for each code, 
    this needs to be discussed with the client developers. Feel
    free to raise any need on this aspect you find during 
    development. Otherwise, basic `OK/ERROR` (plus a descriptive
    message) should be enough.
    
3. Request a `msToken` to the session manager through 
    the `sm/generateToken` api call, but:
    1. Specify as the destination microservice the 
        msID of the API GW, because it will be the api gw the
        microservice that will be validating this token on behalf
        of the client.
    2. Passing your response status object (as a json string) 
        on the QUERY PARAM `data`, as specified for generateToken.
        This way, the status object is transported inside the
        msToken, signed and secured. The client will receive this
        object after validating the token.

4. Redirect to the `ClientCallbackAdd`, passing the generated 
    token on the `msToken` POST param.
